version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/prodject/app
    env_file:
      - ./app/.env
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./app/.env
    command: ["redis-server", "--requirepass", "qwerty1234"]
